import Head from 'next/head';
import { Box, Flex, Text, Title } from '@mantine/core';
import { Roboto } from '@next/font/google';

import DocumentStatusWiseGroup from '@/components/DocumentStatusWiseGroup';

const roboto = Roboto({ subsets: ['latin'], weight: ['100', '300', '400', '500', '700', '900'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={roboto.className}>
        <Box>

          <Title order={1} size={24} weight={500} my={4}>
            Hi Dinesh,
          </Title>

          <Text size={14} >
            Here is a quick status summary of your currently active documents.
          </Text>

          <Flex gap={16} mt={16}>
            <DocumentStatusWiseGroup />
            <DocumentStatusWiseGroup />
            <DocumentStatusWiseGroup />

          </Flex>

        </Box>
      </main>
    </>
  );
}
